# Generated by Django 5.2.3 on 2025-07-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_py',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('orderfood', models.CharField(max_length=200)),
                ('orderdrink', models.CharField(max_length=200)),
            ],
        ),
    ]
