# Generated by Django 5.2.3 on 2025-07-24 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_py',
            new_name='Orderpy',
        ),
    ]
