# Generated by Django 5.2.3 on 2025-07-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_order_py_orderpy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpy',
            old_name='name',
            new_name='per_name',
        ),
    ]
