# Generated by Django 5.2.3 on 2025-07-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_name_orderpy_per_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpy',
            name='drink_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderpy',
            name='food_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderpy',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
